<!DOCTYPE html>
<html lang='cs'>                                                                                                  
  <head>                                        
<script   src="https://code.jquery.com/jquery-1.12.1.js"   integrity="sha256-VuhDpmsr9xiKwvTIHfYWCIQ84US9WqZsLfR4P7qF6O8="   crossorigin="anonymous"></script>                                                                                                                                                                                               
    <title>GEDEON                                                                                                                                                                
    </title>                                                                                                                                          
    <link rel="stylesheet" type="text/css" href="css/faktura.css">                                                                                                                                                                 
    <meta charset='utf-8'>                                                                                                                                                                    
    <meta name='fakturacni_system' content=''>                                                                                                                                                                    
    <meta name='faktury_itsd' content=''>                                                                                                                                                                    
    <meta name='Kamil Klůs' content=''>                                                                                                                                                                    
    <meta name='faktury' content='all'>                                                                                                                                                                    
    <!-- <meta http-equiv='X-UA-Compatible' content='IE=edge'> -->                                                                                                                                                                                                    
    <link href='/favicon.png' rel='shortcut icon' type='image/png'>                                                                                                  
  </head>                                                                                             
  <body> 
<?php
include 'pripojeni.php';
include 'databaze_dodavatel.php';
?>                                                                                                                                                              
    <div class="zahlavi">                                                                                                                                                                                                                                        
      <p class="text_zahlavi_1">Faktura-daňový doklad číslo:                                                                                                                                                                                                                            
        <input type="text" placeholder="Číslo faktury" id="cislo_faktury">                                                                                                                                                                                          
      </p>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
    </div>                                                                                                                                                                              
    <div class="dodavatel">                                                                                                                                                                                                                                    
      <p class="text_dodavatel">Dodavatel:                                                                                                                                                                                                                                
      </p>                                                                                                          
      <div class="logo_itsd">                                                                                                                                      
        <img id="logo" src="obrazky\logo_final_www.png">                                                                                                           
      </div>                                                                                                                                                                                                                               
      <div class="firma_dodavatel_info">                                                                                       
        <table id="dodavatel_tabulka">                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
          <tr><td>
<?php                                                                                                                                                                                                                                                                                                                                                                                                                                                       
echo"<input type='text' placeholder='Dodavatel' id='jmeno_dodavatel' value='$firma_d'>";                                                                                                                                        
echo"<input type='tel' placeholder='Telefonní číslo' id='telefon_dodavatel' value='$telefon_d'></td>";                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
echo"</tr> ";                                                                                                                
echo"<tr><td>";                                                                                                                                                                                                                                                                                                                                                                                                                                                          
echo"<input type='text' placeholder='Adresa' id='adresa_dodavatel' value='$adresa_d'>";                                                                                                                                         
echo"<input type='email' placeholder='E-mail' id='email_dodavatel' value='$email_d'></td>";                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
echo"</tr>";                                                                                                                      
echo"<tr><td>";                                                                                                                                                                                                                                                                                                                                                                                                                                                          
echo"<input type='text' placeholder='Město a PSČ' id='mesto_a_psc_dodavatel' value='$mesto_d'>";                                                                                                                                            
echo"IČO:<input type='text' placeholder='IČO' id='ico_dodavatel' value='$ico_d'></td>";                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
echo"</tr>";                                                                                                                     
echo"<tr><td>";                                                                                                                                                                                                                                                                                                                                                                                                                                                          
echo"<input type='text' placeholder='Stát' id='statni_prislusnost_dodavatel' value='$stat_d'>";                                                                                                                                                     
echo"DIČ:<input type='text' placeholder='DIČ' id='dic_dodavatel' value='$dic_d'></td>";                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
echo"</tr>";                                                                                                                  
echo"</tr>";                                                                                                                    
echo"<tr><td>";                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo"<p>Bankovní spojení:";                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
echo"<input type='text' id='bankovni_spojeni_dodavatel' value='$bankovni_spojeni_d'>";                                                                                                                                                                                                                                                                        
echo"</p></td>";                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
echo"</tr>";
?>                                                                                                                                                                                                                                                                       
        </table>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
      </div>                                                                                                                                                                                                        
    </div> 
<?php
include 'pripojeni.php';
if (isset($_POST['jmeno_odberatele'])) {
include 'databaze_odberatelu.php';
		}else{?>
   <form action="index_formular.php" method="post">                                                                                                                                                                                                                                                              
    <div class="odberatel">                                                                                                                                                                                                                                    
      <p class="text_odberatel">Odběratel:                                                                                                                                                                                                                                
      </p>                                                                                                                                                                                                                                      
      <div class="udaje_firmy_odberatel">                                                                                                                                                                                                                                                                                              
        <table id="odberatel_tabulka">                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
          <tr><td>                                                                                                                                                                                                                                                                                                                                                                                                                                                         
              <input type="text" placeholder="Odběratel" name="jmeno_odberatele" id="jmeno_odberatel">                                                                                                                                      
              <input type="tel" placeholder="Telefon" name="telefon_odberatele" id="telefon_odberatel"></td>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
          </tr>                                                                                                                  
          <tr><td>                                                                                                                                                                                                                                                                                                                                                                                                                                                         
              <input type="text" placeholder="Adresa" name="adresa_odberatele" id="adresa_odberatel">                                                                                                                                      
              <input type="email" placeholder="E-mail" name="email_odberatele" id="email_odberatel"></td>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
          </tr>                                                                                                                   
          <tr><td>                                                                                                                                                                                                                                                                                                                                                                                                                                                         
              <input type="text" placeholder="Město a PSČ" name="mesto_a_psc_odberatele" id="mesto_a_psc_odberatel">                                                                                                                                          
              IČO:<input type="text" placeholder="IČO" name="ico_odberatele" id="ico_odberatel"></td>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
          </tr>                                                                                                                   
          <tr><td>                                                                                                                                                                                                                                                                                                                                                                                                                                                        
              <input type="text" placeholder="Stát" name="statni_prislusnost_odberatele" id="statni_prislusnost_odberatele">                                                                                                                                                     
              DIČ:<input type="text" placeholder="DIČ" name="dic_odberatele" id="dic_odberatel"></td>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
          </tr>                                                                                                                                                                                                                                                                                                
        </table> 
        <?php 
  		?>                                                                                                                                                                                                                                                                                                                                                     
      </div>                                                                                                                                                                      
    </div>   
        </form> 
        <?php }	//}
		//}?>    
                                                                                                                                                                                                       
    <div class="info_faktura">                                                                                                                    
      <div class="cara">                                                                                                                                             
      </div>                                                                                                                                                
      <table id="info_faktura_tabulka">                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
        <tr>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <td>Způsob úhrady:</td><td>            
            <select id="zpusob_uhrady">                                                                                                                                                                                                                                                                                                                                                                                                                                
              <option value="prevodem" selected="selected">Převodem                                                                                                                                                                                                                                                                                                                                                                                                                      
              </option>                                                                                                                                                                                                                                                                                                                                                                                                                                  
              <option value="kartou">Kartou                                                                                                                                                                                                                                                                                                                                                                                                                      
              </option>                                                                                                                                                                                                                                                                                                                                                                                                                                    
              <option value="hotove">Hotově                                                                                                                                                                                                                                                                                                                                                                                                                      
              </option>                                                                                                                                                                                                                                                                                                                                                                                                                                      
              <option value="dobirkou">Dobírkou                                                                                                                                                                                                                                                                                                                                                                                                                      
              </option>                                                                                                                                                                                                                                                                                                                                                                                                                                        
              <option value="zapoctem">Zápočtem                                                                                                                                                                                                                                                                                                                                                                                                                      
              </option>                                                                                                                                                                                                                                                                                                                                                                                                                                          
              <option value="zalohou">Zálohou                                                                                                                                                                                                                                                                                                                                                                                                                      
              </option>                                                                                                                                                                                                                                                                                                                                                                           
            </select></td>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <td>Konstantní symbol:</td><td>            
            <input type="text" placeholder="KS" id="konstatni_symbol"></td>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <td>Datum splatnosti:</td><td>            
            <input type="text" placeholder="Datum" id="datum_splatnosti"></td>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </td>                                                              
        </tr>                                                                                                    
        <tr><td>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Datum vystavení:</td><td>            
            <input type="text" placeholder="Datum" id="datum_vystaveni"></td>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <td>Variabilní symbol:</td><td>            
            <input type="text" placeholder="VS" id="variabilni_symbol"></td>
            <td>DUZP:</td><td>            
            <input type="text" placeholder="DUZP" id="DUZP"></td>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </td>                                                               
        </tr>                                                                                                                                                                                                                                                                              
      </table>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
    </div>                                                                                                                                                                                                                           
    <div class="vyuctovani">                                                                                                       
      <div class="cara">                                                                                                                                             
      </div>                                                                                                       
      <div class="tabulka">                                                                                                                               
        <p class="fakturujeme">Fakturujeme Vám za dodané zboží a služby                                                                                                                     
        </p>                                                                                                                                                                                                                                                                                                                                                                      
        <table id="tabulka_zbozi_sluzeb">                                                                                                                                                                                                                                                                                                                                
          <tr> 
          <td width="2%"></td>                                     
            <td class="ohraniceni">          Označení dodávky</td>                                      
            <td class="ohraniceni">          Počet m. j.</td>                                      
            <td class="ohraniceni">          Cena za m. j.</td>                                      
            <td class="ohraniceni">          DPH %</td><td>Bez DPH</td>                                      
            <td class="ohraniceni">          DPH</td>                                      
            <td class="ohraniceni">          Celkem                                             
              </td class="ohraniceni">                                                                                                                                                                                                                                                                                                                 
          </tr>                                                                                                                                                                                                                                                                                                                                
          <tr>
          <td width="1%"></td>                                      
            <td class="ohraniceni">                                                                                                                                                                                                                                                                                                                                                                                                                                                         
              <input type="text"></td>                                      
            <td class="ohraniceni">                                                                                                                                                                                                                                                                                                                                                                                                                                                         
              <input type="text"></td>                                      
            <td class="ohraniceni">                                                                                                                                                                                                                                                                                                                                                                                                                                                         
              <input type="text"></td>                                      
            <td class="ohraniceni">                                                                                                                                                                                                                                                                                                                                                                                                                                                         
              <input type="text"></td>                                      
            <td class="ohraniceni">                                                                                                                                                                                                                                                                                                                                                                                                                                                         
              <input type="text"></td>                                      
            <td class="ohraniceni">                                                                                                                                                                                                                                                                                                                                                                                                                                                         
              <input type="text"></td>                                      
            <td class="ohraniceni">                                                                                                                                                                                                                                                                                                                                                                                                                                                         
              <input type="text">                                            
              </td class="ohraniceni">                                                                                                                                                                                                                                                                                                                         
          </tr>                                                                                                                                                                                                                                                                    
        </table>                                                                                                                                                                                                                                                            
                                           
<script> 
   $('document').ready(function() {
  $('.pridej').click(function() {
      $("#tabulka_zbozi_sluzeb").append('<tr style="border-bottom:1pt solid lightgray;"><td><input type="button" class="button_odeber" value="-" onclick="deleteRow(this)"></td><td><input type="text"/> </td><td><input type="text"/></td><td><input type="text"/></td><td><input type="text"/>  </td><td><input type="text"/>  </td><td><input type="text"/>  </td><td><input type="text"/>  </td></tr>');
   });
})      
    </script> 
    <script>
function deleteRow(r) {
    var i = r.parentNode.parentNode.rowIndex;
    document.getElementById("tabulka_zbozi_sluzeb").deleteRow(i);
}
</script>
    <button type="button" id="button_pridej" class="button pridej">+</button>                                                                                                                                                                                                                                                                       
        <p class="zbozi_zustava">Zboží zůstává až do úplného uhrazení majetkem dodavatele. Při zpožděné úhradě Vám budeme účtovat penále ve výši 0.05% za každý započatý den prodlení                                                                                                                                                                                                                                     
        </p>                                                                                                     
      </div>                                                                                          
      <div class="cenik">                                                                                                                                                                                                                                     
        <table id="tabulka_cenik">                                                                                                                                                                                                                                                                                                    
          <tr id="cenik_popis" class="ohraniceni"><td></td>                                      
            <td class="ohraniceni">Základ</td>                                      
            <td class="ohraniceni">Výše DPH</td><td>Celkem</td>                                                                                                                                                                                                                                                                                                                       
          </tr>                                                                                                                                                                                                                                                                                                               
          <tr class="ohraniceni">                                      
            <td class="ohraniceni">Základní sazba:</td>            
            <td class="ohraniceni">                                                                                                                                                                                                                                                                                                                                                                                                                                                           
              <input type="text"></td>                                          
            <td class="ohraniceni">                                                                                                                                                                                                                                                                                                                                                                                                                                                           
              <input type="text"></td>                                          
            <td class="ohraniceni">                                                                                                                                                                                                                                                                                                                                                                                                                                                           
              <input type="text"></td>                                                                                                                                                                                                                                                                                                                       
          </tr>                                                                                                                                                                                                                                                                                                               
          <tr class="ohraniceni">                                      
            <td class="ohraniceni">CELKEM</td>                                      
            <td class="ohraniceni">                                                                                                                                                                                                                                                                                                                                                                                                                                                       
              <input type="text"></td>                                      
            <td class="ohraniceni">                                                                                                                                                                                                                                                                                                                                                                                                                                                       
              <input type="text"></td>                                      
            <td class="ohraniceni">                                                                                                                                                                                                                                                                                                                                                                                                                                                       
              <input type="text"></td>                                                                                                                                                                                                                                                                                                                       
          </tr>                                                                                                                                                                                                                                               
        </table>                                            
        <p class="poznamka" >Pozn.: Částky jsou včetně hodnot zaokrouhlení                  
        </p>                                                                                                    
        <p class="celkova_uhrada">Celkem k úhradě:                                                                                                                                     
          <input type="text" maxlength="12" id="uhrada"> Kč                                                                                                            
        </p>                                                                                                                                                                                     
      </div>  
      <button type="submit" class="btn btn-success" value="add" name="add" id="add">Vložit záznam</button>                                                                   
    </div> 
                                                                                                                                                                                  
    <div class="zapati">                                                                                                                                                                                                                                                                                        
      <p>Společnost je zapsána v obchodním rejstříku vedeném Krajský soudem v Plzni, oddíl C, vložka 33892                                                                                                                                                                                                               
      </p>                                                                                                                                                                                                                                                                                                                   
      <div class="cara">                                                                                                                                             
      </div>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
      <div class="zpracovano">Zpracováno systémem GEDEON itsd.cz              
      </div>                    
      <div class="strana"> Strana1/1              
      </div>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
    </div>                                                                                                    
  </body>
</html>